restaurant:
  name: French Restaurant
  capacity: 75
  description: "Name: ${restaurant.name}. Capacity: ${restaurant.capacity}. Owner: ${restaurant.owner:Andrew}"
  menu:
    itemsString: Spaghetti Bolognese, Caesar Salad, Grilled Salmon